# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.3
  - 2.7
  - 2.6

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r djangocms_export_objects/tests/requirements.txt
  - pip install python-coveralls coverage

# command to run tests, e.g. python setup.py test
script: coverage run --rcfile=coverage.rc setup.py test

after_success:
  coveralls --config_file=coverage.rc

matrix:
  allow_failures:
    - python: 3.3